export const countries = [
  { code: "AF", name: "Afghanistan", currency: "AFN", flag: "🇦🇫" },
  { code: "AL", name: "Albania", currency: "ALL", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", currency: "DZD", flag: "🇩🇿" },
  { code: "AD", name: "Andorra", currency: "EUR", flag: "🇦🇩" },
  { code: "AO", name: "Angola", currency: "AOA", flag: "🇦🇴" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", currency: "ARS", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", currency: "AMD", flag: "🇦🇲" },
  { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺" },
  { code: "AT", name: "Austria", currency: "EUR", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", currency: "BSD", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", currency: "BHD", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", currency: "BDT", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", currency: "BBD", flag: "🇧🇧" },
  { code: "BY", name: "Belarus", currency: "BYN", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", currency: "EUR", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", currency: "BZD", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", currency: "XOF", flag: "🇧🇯" },
  { code: "BT", name: "Bhutan", currency: "BTN", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", currency: "BOB", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", currency: "BWP", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷" },
  { code: "BN", name: "Brunei Darussalam", currency: "BND", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", currency: "BGN", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", currency: "BIF", flag: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", currency: "CVE", flag: "🇨🇻" },
  { code: "KH", name: "Cambodia", currency: "KHR", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", currency: "XAF", flag: "🇨🇲" },
  { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦" },
  { code: "CF", name: "Central African Republic", currency: "XAF", flag: "🇨🇫" },
  { code: "TD", name: "Chad", currency: "XAF", flag: "🇹🇩" },
  { code: "CL", name: "Chile", currency: "CLP", flag: "🇨🇱" },
  { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", currency: "COP", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", currency: "KMF", flag: "🇰🇲" },
  { code: "CD", name: "Congo, Dem. Rep. of the", currency: "CDF", flag: "🇨🇩" },
  { code: "CG", name: "Congo, Rep. of the", currency: "XAF", flag: "🇨🇬" },
  { code: "CR", name: "Costa Rica", currency: "CRC", flag: "🇨🇷" },
  { code: "HR", name: "Croatia", currency: "EUR", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", currency: "CUP", flag: "🇨🇺" },
  { code: "CY", name: "Cyprus", currency: "EUR", flag: "🇨🇾" },
  { code: "CZ", name: "Czechia", currency: "CZK", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", currency: "DKK", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", currency: "DJF", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", currency: "XCD", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", currency: "USD", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬" },
  { code: "SV", name: "El Salvador", currency: "USD", flag: "🇸🇻" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", currency: "ERN", flag: "🇪🇷" },
  { code: "EE", name: "Estonia", currency: "EUR", flag: "🇪🇪" },
  { code: "SZ", name: "Eswatini", currency: "SZL", flag: "🇸🇿" },
  { code: "ET", name: "Ethiopia", currency: "ETB", flag: "🇪🇹" },
  { code: "FJ", name: "Fiji", currency: "FJD", flag: "🇫🇯" },
  { code: "FI", name: "Finland", currency: "EUR", flag: "🇫🇮" },
  { code: "FR", name: "France", currency: "EUR", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", currency: "XAF", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", currency: "GMD", flag: "🇬🇲" },
  { code: "GE", name: "Georgia", currency: "GEL", flag: "🇬🇪" },
  { code: "DE", name: "Germany", currency: "EUR", flag: "🇩🇪" },
  { code: "GH", name: "Ghana", currency: "GHS", flag: "🇬🇭" },
  { code: "GR", name: "Greece", currency: "EUR", flag: "🇬🇷" },
  { code: "GD", name: "Grenada", currency: "XCD", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", currency: "GTQ", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", currency: "GNF", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", currency: "GYD", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", currency: "HTG", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", currency: "HNL", flag: "🇭🇳" },
  { code: "HU", name: "Hungary", currency: "HUF", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", currency: "ISK", flag: "🇮🇸" },
  { code: "IN", name: "India", currency: "INR", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", currency: "IDR", flag: "🇮🇩" },
  { code: "IR", name: "Iran", currency: "IRR", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", currency: "IQD", flag: "🇮🇶" },
  { code: "IE", name: "Ireland", currency: "EUR", flag: "🇮🇪" },
  { code: "IT", name: "Italy", currency: "EUR", flag: "🇮🇹" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF", flag: "🇨🇮" },
  { code: "JM", name: "Jamaica", currency: "JMD", flag: "🇯🇲" },
  { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", currency: "JOD", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", currency: "KES", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", currency: "AUD", flag: "🇰🇮" },
  {
    code: "KP",
    name: "Korea, Dem. People's Rep. of",
    currency: "KPW",
    flag: "🇰🇵",
  },
  { code: "KR", name: "Korea, Rep. of", currency: "KRW", flag: "🇰🇷" },
  { code: "KW", name: "Kuwait", currency: "KWD", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", flag: "🇰🇬" },
  { code: "LA", name: "Lao People's Dem. Rep.", currency: "LAK", flag: "🇱🇦" },
  { code: "LV", name: "Latvia", currency: "EUR", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", currency: "LBP", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", currency: "LSL", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", currency: "LRD", flag: "🇱🇷" },
  { code: "LY", name: "Libya", currency: "LYD", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", currency: "EUR", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", currency: "EUR", flag: "🇱🇺" },
  { code: "MG", name: "Madagascar", currency: "MGA", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", currency: "MWK", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", currency: "MYR", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", currency: "MVR", flag: "🇲🇻" },
  { code: "ML", name: "Mali", currency: "XOF", flag: "🇲🇱" },
  { code: "MT", name: "Malta", currency: "EUR", flag: "🇲🇹" },
  { code: "MH", name: "Marshall Islands", currency: "USD", flag: "🇲🇭" },
  { code: "MR", name: "Mauritania", currency: "MRU", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", currency: "MUR", flag: "🇲🇺" },
  { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽" },
  {
    code: "FM",
    name: "Micronesia (Fed. States of)",
    currency: "USD",
    flag: "🇫🇲",
  },
  { code: "MD", name: "Moldova", currency: "MDL", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", currency: "EUR", flag: "🇲🇨" },
  { code: "MN", name: "Mongolia", currency: "MNT", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", currency: "EUR", flag: "🇲🇪" },
  { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", currency: "MZN", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", currency: "MMK", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", currency: "NAD", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", currency: "AUD", flag: "🇳🇷" },
  { code: "NP", name: "Nepal", currency: "NPR", flag: "🇳🇵" },
  { code: "NL", name: "Netherlands", currency: "EUR", flag: "🇳🇱" },
  { code: "NZ", name: "New Zealand", currency: "NZD", flag: "🇳🇿" },
  { code: "NI", name: "Nicaragua", currency: "NIO", flag: "🇳🇮" },
  { code: "NE", name: "Niger", currency: "XOF", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", currency: "NGN", flag: "🇳🇬" },
  { code: "MK", name: "North Macedonia", currency: "MKD", flag: "🇲🇰" },
  { code: "NO", name: "Norway", currency: "NOK", flag: "🇳🇴" },
  { code: "OM", name: "Oman", currency: "OMR", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", currency: "PKR", flag: "🇵🇰" },
  { code: "PW", name: "Palau", currency: "USD", flag: "🇵🇼" },
  { code: "PS", name: "Palestine, State of", currency: "ILS", flag: "🇵🇸" }, // Included as requested
  { code: "PA", name: "Panama", currency: "PAB", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", currency: "PYG", flag: "🇵🇾" },
  { code: "PE", name: "Peru", currency: "PEN", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", currency: "PHP", flag: "🇵🇭" },
  { code: "PL", name: "Poland", currency: "PLN", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", currency: "EUR", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", currency: "QAR", flag: "🇶🇦" },
  { code: "RO", name: "Romania", currency: "RON", flag: "🇷🇴" },
  { code: "RU", name: "Russian Federation", currency: "RUB", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", currency: "RWF", flag: "🇷🇼" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", flag: "🇱🇨" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    currency: "XCD",
    flag: "🇻🇨",
  },
  { code: "WS", name: "Samoa", currency: "WST", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", currency: "EUR", flag: "🇸🇲" },
  { code: "ST", name: "Sao Tome and Principe", currency: "STD", flag: "🇸🇹" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦" },
  { code: "SN", name: "Senegal", currency: "XOF", flag: "🇸🇳" },
  { code: "RS", name: "Serbia", currency: "RSD", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", currency: "SCR", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", currency: "SLL", flag: "🇸🇱" },
  { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬" },
  { code: "SK", name: "Slovakia", currency: "EUR", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", currency: "EUR", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", flag: "🇸🇧" },
  { code: "SO", name: "Somalia", currency: "SOS", flag: "🇸🇴" },
  { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦" },
  { code: "SS", name: "South Sudan", currency: "SSP", flag: "🇸🇸" },
  { code: "ES", name: "Spain", currency: "EUR", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", flag: "🇱🇰" },
  { code: "SD", name: "Sudan", currency: "SDG", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", currency: "SRD", flag: "🇸🇷" },
  { code: "SE", name: "Sweden", currency: "SEK", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭" },
  { code: "SY", name: "Syrian Arab Republic", currency: "SYP", flag: "🇸🇾" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania, United Rep. of", currency: "TZS", flag: "🇹🇿" },
  { code: "TH", name: "Thailand", currency: "THB", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", currency: "USD", flag: "🇹🇱" },
  { code: "TG", name: "Togo", currency: "XOF", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", currency: "TOP", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", currency: "TND", flag: "🇹🇳" },
  { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", flag: "🇹🇲" },
  { code: "TV", name: "Tuvalu", currency: "AUD", flag: "🇹🇻" },
  { code: "UG", name: "Uganda", currency: "UGX", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", currency: "UAH", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧" },
  { code: "US", name: "United States", currency: "USD", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", currency: "UYU", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", flag: "🇺🇿" },
  { code: "VU", name: "Vanuatu", currency: "VUV", flag: "🇻🇺" },
  { code: "VE", name: "Venezuela", currency: "VES", flag: "🇻🇪" },
  { code: "VN", name: "Viet Nam", currency: "VND", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", currency: "YER", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", currency: "ZMW", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", flag: "🇿🇼" },
  { code: "VA", name: "Vatican City", currency: "EUR", flag: "🇻🇦" }, // Holy See (Vatican City)
  { code: "AX", name: "Åland Islands", currency: "EUR", flag: "🇦🇽" },
  { code: "AS", name: "American Samoa", currency: "USD", flag: "🇦🇸" },
  { code: "AI", name: "Anguilla", currency: "XCD", flag: "🇦🇮" },
  { code: "AQ", name: "Antarctica", currency: "", flag: "🇦🇶" }, // No official currency
  { code: "AW", name: "Aruba", currency: "AWG", flag: "🇦🇼" },
  { code: "BM", name: "Bermuda", currency: "BMD", flag: "🇧🇲" },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    currency: "USD",
    flag: "🇧🇶",
  },
  { code: "BV", name: "Bouvet Island", currency: "NOK", flag: "🇧🇻" }, // Norwegian territory
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    currency: "USD",
    flag: "🇮🇴",
  },
  { code: "VG", name: "British Virgin Islands", currency: "USD", flag: "🇻🇬" },
  { code: "KY", name: "Cayman Islands", currency: "KYD", flag: "🇰🇾" },
  { code: "CX", name: "Christmas Island", currency: "AUD", flag: "🇨🇽" },
  { code: "CC", name: "Cocos (Keeling) Islands", currency: "AUD", flag: "🇨🇨" },
  { code: "CK", name: "Cook Islands", currency: "NZD", flag: "🇨🇰" },
  { code: "CW", name: "Curaçao", currency: "ANG", flag: "🇨🇼" },
  {
    code: "FK",
    name: "Falkland Islands (Malvinas)",
    currency: "FKP",
    flag: "🇫🇰",
  },
  { code: "FO", name: "Faroe Islands", currency: "DKK", flag: "🇫🇴" },
  { code: "GF", name: "French Guiana", currency: "EUR", flag: "🇬🇫" },
  { code: "PF", name: "French Polynesia", currency: "XPF", flag: "🇵🇫" },
  {
    code: "TF",
    name: "French Southern Territories",
    currency: "EUR",
    flag: "🇹🇫",
  },
  { code: "GI", name: "Gibraltar", currency: "GIP", flag: "🇬🇮" },
  { code: "GL", name: "Greenland", currency: "DKK", flag: "🇬🇱" },
  { code: "GP", name: "Guadeloupe", currency: "EUR", flag: "🇬🇵" },
  { code: "GU", name: "Guam", currency: "USD", flag: "🇬🇺" },
  { code: "GG", name: "Guernsey", currency: "GBP", flag: "🇬🇬" },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    currency: "AUD",
    flag: "🇭🇲",
  },
  { code: "HK", name: "Hong Kong", currency: "HKD", flag: "🇭🇰" },
  { code: "IM", name: "Isle of Man", currency: "GBP", flag: "🇮🇲" },
  { code: "JE", name: "Jersey", currency: "GBP", flag: "🇯🇪" },
  { code: "MO", name: "Macao", currency: "MOP", flag: "🇲🇴" },
  { code: "MQ", name: "Martinique", currency: "EUR", flag: "🇲🇶" },
  { code: "YT", name: "Mayotte", currency: "EUR", flag: "🇾🇹" },
  { code: "MS", name: "Montserrat", currency: "XCD", flag: "🇲🇸" },
  { code: "NC", name: "New Caledonia", currency: "XPF", flag: "🇳🇨" },
  { code: "NU", name: "Niue", currency: "NZD", flag: "🇳🇺" },
  { code: "NF", name: "Norfolk Island", currency: "AUD", flag: "🇳🇫" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", flag: "🇲🇵" },
  { code: "PN", name: "Pitcairn", currency: "NZD", flag: "🇵🇳" },
  { code: "PR", name: "Puerto Rico", currency: "USD", flag: "🇵🇷" },
  { code: "RE", name: "Réunion", currency: "EUR", flag: "🇷🇪" },
  { code: "BL", name: "Saint Barthélemy", currency: "EUR", flag: "🇧🇱" },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    currency: "SHP",
    flag: "🇸🇭",
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    currency: "EUR",
    flag: "🇵🇲",
  },
  {
    code: "MF",
    name: "Saint Martin (French part)",
    currency: "EUR",
    flag: "🇲🇫",
  },
  {
    code: "SX",
    name: "Sint Maarten (Dutch part)",
    currency: "ANG",
    flag: "🇸🇽",
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    currency: "GBP",
    flag: "🇬🇸",
  },
  { code: "SJ", name: "Svalbard and Jan Mayen", currency: "NOK", flag: "🇸🇯" },
  {
    code: "TW",
    name: "Taiwan, Province of China",
    currency: "TWD",
    flag: "🇹🇼",
  }, // Often considered a de facto independent state
  { code: "TK", name: "Tokelau", currency: "NZD", flag: "🇹🇰" },
  { code: "TC", name: "Turks and Caicos Islands", currency: "USD", flag: "🇹🇨" },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    currency: "USD",
    flag: "🇺🇲",
  },
  {
    code: "VI",
    name: "United States Virgin Islands",
    currency: "USD",
    flag: "🇻🇮",
  },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF", flag: "🇼🇫" },
  { code: "EH", name: "Western Sahara", currency: "MAD", flag: "🇪🇭" }, // Disputed territory
  { code: "XK", name: "Kosovo", currency: "EUR", flag: "🇽🇰" }, // Partially recognized
];
